apiVersion: v1
kind: Service
metadata:
  name: booking-api
  namespace: airline-observability
  labels:
    app: booking-api
spec:
  type: ClusterIP
  selector:
    app: booking-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
