apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "airline-booking.fullname" . }}-otel-env
  labels:
    {{- include "airline-booking.labels" . | nindent 4 }}
data:
  OTEL_SERVICE_NAME: {{ .Values.otel.serviceName | quote }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.otel.exporterEndpoint | quote }}
  OTEL_EXPORTER_OTLP_PROTOCOL: {{ .Values.otel.exporterProtocol | quote }}
  OTEL_RESOURCE_ATTRIBUTES: {{ .Values.otel.resourceAttributes | quote }}
  OTEL_TRACES_EXPORTER: {{ .Values.otel.tracesExporter | quote }}
  OTEL_METRICS_EXPORTER: {{ .Values.otel.metricsExporter | quote }}
  OTEL_LOGS_EXPORTER: {{ .Values.otel.logsExporter | quote }}
